- hosts: all
  gather_facts: False
  tasks:
    - name: Update the packages"
      apt:
        update_cache: yes

- hosts: DB
  roles:
    - database

- hosts: BACKEND
  roles:
    - backend

- hosts: Web
  roles:
    - frontend
