---
# tasks file for wordpress

- name: Install required software
  apt: 
     name:
       - apache2
       - php-mysql
       - php
       - libapache2-mod-php  
       - python3-mysqldb
       - mysql-client
     state: present
     autoclean: yes
  tags: apache

- name: Install php extensions
  apt: 
    name:
      - php-gd
      - php-ssh2
      - php-curl
      - php-mbstring
      - php-xml
      - php-xmlrpc 
      - php-soap
      - php-intl
      - php-zip
    state: present
    autoclean: yes
  tags: php

- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/   copy=no

- name: Update default Apache site
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="		DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php

- name: Update WordPress config file
  lineinfile:
    dest=/var/www/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - {'regexp': "define( 'DB_NAME', 'database_name_here' );", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
    - {'regexp': "define( 'DB_USER', 'username_here' );", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
    - {'regexp': "define( 'DB_PASSWORD', 'password_here' );", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
    - {'regexp': "define( 'DB_HOST', 'localhost' );", 'line': "define('DB_HOST', '{{wp_mysql_host}}');"}
